# settings.py
# A file to hold all of my constants.

#Files and directories
NHANES_DATA_PATH = '/Users/stephenwood/Dropbox/School/BETR Global/nhanes_data'

# Time params.
HOURS_IN_YEAR = 8760

DEFAULT_START_YEAR = 1930

NUMBER_OF_HUMANS = 8

# Human params
HUMAN_MAX_AGE = 80
DEFAULT_AGE_AT_MODEL_START = 0

DEFAULT_AGE_SPREAD = 10
DEFAULT_NURSE_DURATION_IN_H = 182 * 24
DONT_KNOW_CODE = 999
BLANK_VALUE = 9999
NUMBER_MAX_BIRTH = 5

HUMAN_CONCENTRATION_FILE_NAMES = ['CMAN.txt', 'CWOMAN.txt']


# Codes for NHANES

YES_CODE = '1'
NO_CODE = '2'

NUMBER_OF_BIRTHS_CODE = 'RHD170'
AGE_FIRST_CHILD_CODE = 'RHQ180'
AGE_LAST_CHILD_CODE = 'RHQ190'
PCB153_CODE = 'LBX153LA'
AGE_CODE = 'RIDAGEYR'
GENDER_CODE = 'RIAGENDR'
BMI_CODE = 'BMXBMI'

# food Codes

SHELLFISH_CODE = 'DRD340'
FISH_CODE = 'DRD360'